---
title: "R Notebook"
output: html_notebook
---


```{r}
n1_size = 150
n1_answers = 44

n2_size = 150
n2_answers = 70

n1_proportion = n1_answers / n1_size
n2_proportion = n2_answers / n2_size

n1_proportion
n2_proportion

prop.test(c(70, 44), c(150, 150), conf.level = 0.90, correct = TRUE)
```
```{r}

data = read.csv("chi2test1.csv", header = FALSE, sep = ",")
tab = table(data)

data_matrix = as.matrix(data)

table(data_matrix)

```

```{r}
chisq.test(table(data))
```

```{r}
chisq.test(as.matrix(table(data)))
```

H0 - variables are independ (p-value = 2.3e-6 < 5% conf level), so we need to reject this H0 
H1 - variables are depend


## Problem 2
Q1: 3 (because p-value < 5%) (H0)
Q2: 




## Problem 3

```{r}
X = read.csv("Pred1.csv", header = F, sep = ",")

X
```

```{r}
X_train = X[1:1498,]
X_test = X[1498:1698,]
```


```{r}
lm_fitted = lm.fit(X_train[, 1], X_train[, 2:3])
```



```{r}
lg_model = glm(V1~V2+V3, data = X_train, family = "binomial" )
```


```{r}
summary(lg_model)
```

Q2 = V2 Estimate Std ± 0.19514
```{r}
2 * 0.09757
```


Q3 = 0.34138597 (1698 - rownum)
```{r}
predict(lg_model, X_test[201, 1:3], type = "response")
```


Q4: 
```{r}
predicts = predict(lg_model, X_test, type = "response")

predicted_values = rep(0, length(predicts))
predicted_values[predicts > 0.5] = 1

predicted_values

```

```{r}
X_test[, 1]
```

```{r}
table(predicted_values, X_test[,1])
```


```{r}
length(predicted_values)

error_rate = (80 + 45) / length(predicted_values)

error_rate
```

Q5: 

```{r}
library(MASS)

lda_model = lda(V1 ~ V2 + V3, data = X_train)

lda_model
```

```{r}
lda_predicts = as.numeric(predict(lda_model, X_test)$class) - 1

lda_predicts
```
```{r}
table(lda_predicts, X_test[,1])
```

```{r}
length(predicted_values)

error_rate = (80 + 45) / length(predicted_values)

error_rate
```
```

Q6:











